"use client";

import React, { createContext, useContext, useState, useEffect } from "react";
import type { Operator, Weapon, Gadget } from "@/data/types";
import { UI_TRANSLATIONS, getTranslation } from "@/data/i18n";
import type { Language } from "@/data/i18n";

// Dynamically import translations (they are generated by translate-db.mjs)
import rawDe from "../../R6_bundle/R6_complete_de.json";
import rawEn from "../../R6_bundle/R6_complete_en.json";
import rawFr from "../../R6_bundle/R6_complete_fr.json";

const rawData = {
  de: rawDe,
  en: rawEn,
  fr: rawFr
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof UI_TRANSLATIONS, params?: Record<string, string | number>) => string;
  operators: Operator[];
  weapons: Weapon[];
  gadgets: Gadget[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("de");
  const [mounted, setMounted] = useState(false);

  // Load language preference from localStorage
  useEffect(() => {
    const saved = localStorage.getItem("r6codex_lang");
    if (saved === "de" || saved === "en" || saved === "fr") {
      setLanguageState(saved);
    } else {
      // Fallback to browser language
      const browserLang = navigator.language.slice(0, 2);
      if (browserLang === "en" || browserLang === "fr") {
        setLanguageState(browserLang);
      }
    }
    setMounted(true);
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("r6codex_lang", lang);
  };

  const t = (key: keyof typeof UI_TRANSLATIONS, params?: Record<string, string | number>) => {
    let text = getTranslation(key, language);
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  };

  const db = rawData[language];

  // Title-case normalization for weapons (matching src/data/r6.ts logic)
  const titleCase = (s?: string | null): string | undefined => {
    if (!s) return undefined;
    return s
      .toLowerCase()
      .replace(/\b\w/g, (c) => c.toUpperCase())
      .replace(/\bSmg\b/i, "SMG");
  };

  // Process data to match structure
  const localizedOperators = db.operators as Operator[];
  const localizedWeapons = (db.weapons as any[]).map((w) => ({
    ...w,
    type: titleCase(w.type) ?? titleCase(w.subtype ?? undefined),
  })) as Weapon[];
  const localizedGadgets = db.gadgets as Gadget[];

  // Render a placeholder or the app after mount to avoid hydration mismatch
  if (!mounted) {
    return (
      <LanguageContext.Provider
        value={{
          language: "de",
          setLanguage,
          t,
          operators: rawData["de"].operators as Operator[],
          weapons: (rawData["de"].weapons as any[]).map((w) => ({
            ...w,
            type: titleCase(w.type) ?? titleCase(w.subtype ?? undefined),
          })) as Weapon[],
          gadgets: rawData["de"].gadgets as Gadget[]
        }}
      >
        <div style={{ visibility: "hidden" }}>{children}</div>
      </LanguageContext.Provider>
    );
  }

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        operators: localizedOperators,
        weapons: localizedWeapons,
        gadgets: localizedGadgets
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
